name: Create Development builds

on: 
  push:
    branches: ["main"]

jobs: 
  android_development_build: 
    name: Build Android
    type: build
    params:
      platform: android
      profile: development
      